use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::Path;

use tempfile::tempdir;
use wash_load::{
    load_and_validate_config, load_data, validate_records, AuditService,
    BasicReviewChartRenderer, BuiltinPolicyExecutor, CheckpointStore, CleanerStage,
    CommitArtifacts,
    DefaultAuditService, DefaultCleanerStage, DefaultLlmReportService, DefaultLoadErrorAuditMapper,
    DefaultPerformanceSummaryBuilder, DefaultReviewStage, DefaultVersioningService,
    FileAuditCsvSampler, FileAuditLogWriter, FileDisabledIssueProvider, FileLlmReportStore,
    FileReviewReportStore, FileHistoryStore, HandlingConfig, IssueType, LlmClient,
    LlmGenerateRequest, LlmGenerateResponse, LlmReportConfig, LlmReportError, LlmReportService,
    RecoveryService, ReviewChartConfig, ReviewChartType, ReviewConfig, ReviewPreviewConfig,
    ReviewStage, RuleNamePolicyResolver, RunMode, StaticRuleRegistry, TopKSummaryBuilder,
    ValidationContext, ValidationPlan, ValidationRegistry, VersionCommitInput, VersioningConfig,
    VersioningService,
};

fn write_file(path: &Path, content: &str) {
    fs::write(path, content).expect("write file");
}

fn write_cleaned_csv(path: &Path, records: &[wash_load::Record]) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create output dir");
    }

    let mut out = String::from("date,ticker,open,high,low,close,vwap,volume,turnover,status\n");
    for row in records {
        out.push_str(&format!(
            "{},{},{},{},{},{},{},{},{},{}\n",
            row.date,
            row.ticker,
            row.open,
            row.high,
            row.low,
            row.close,
            row.vwap,
            row.volume,
            row.turnover,
            match &row.status {
                wash_load::TradeStatus::Normal => "NORMAL".to_string(),
                wash_load::TradeStatus::Halted => "HALTED".to_string(),
                wash_load::TradeStatus::Delisted => "DELISTED".to_string(),
                wash_load::TradeStatus::Other(v) => v.clone(),
            }
        ));
    }

    fs::write(path, out).expect("write cleaned csv");
}

fn write_summary_json(path: &Path, summary: &wash_load::PerformanceSummary) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create summary dir");
    }

    let payload = format!(
        "{{\n  \"total_rows\": {},\n  \"total_issues\": {},\n  \"processed_issues\": {},\n  \"unresolved_issues\": {},\n  \"disabled_issues\": {},\n  \"load_error_count\": {},\n  \"total_time_ms\": {},\n  \"throughput_rows_per_sec\": {}\n}}\n",
        summary.total_rows,
        summary.total_issues,
        summary.processed_issues,
        summary.unresolved_issues,
        summary.disabled_issues,
        summary.load_error_count,
        summary.total_time_ms,
        summary.throughput_rows_per_sec,
    );

    fs::write(path, payload).expect("write summary json");
}

fn pipeline_registry() -> StaticRuleRegistry {
    StaticRuleRegistry::new(
        vec![
            "MissingDatesRule",
            "DuplicateDatesRule",
            "NonTradingDayRule",
            "HighLowLogicRule",
            "NegativePriceRule",
            "TickSizeRule",
            "VwapRangeRule",
        ],
        vec!["DataIntegrity", "IntraBarLogic"],
    )
}

fn default_validation_ctx() -> ValidationContext {
    ValidationContext::new(
        vec![
            "2026-03-03".to_string(),
            "2026-03-04".to_string(),
            "2026-03-05".to_string(),
            "2026-03-06".to_string(),
            "2026-03-07".to_string(),
        ],
        "0.01".parse().expect("decimal"),
    )
}

#[derive(Debug, Clone, Copy)]
struct MockLlmClient;

impl LlmClient for MockLlmClient {
    fn generate(&self, req: &LlmGenerateRequest) -> Result<LlmGenerateResponse, LlmReportError> {
        assert_eq!(req.model, "mock-gpt");
        assert!(req.prompt.contains("top_issue_types"));
        Ok(LlmGenerateResponse {
            text: "# Mock Full Pipeline Report\n\n- This report is generated by mock LLM client."
                .to_string(),
            usage_prompt_tokens: Some(120),
            usage_completion_tokens: Some(64),
            latency_ms: Some(5),
        })
    }
}

#[test]
fn full_pipeline_happy_path_with_mocked_llm_and_versioning_snapshot() {
    let dir = tempdir().expect("tempdir");

    // 1) Prepare input CSV and YAML config as a real CLI user would do.
    let csv_path = dir.path().join("input/raw.csv");
    fs::create_dir_all(csv_path.parent().expect("parent")).expect("mkdir");
    write_file(
        &csv_path,
        "date,ticker,open,high,low,close,vwap,volume,turnover,status\n\
2026-03-03,000001.SZ,10.00,10.30,9.90,10.10,10.05,1000,10000,NORMAL\n\
2026-03-03,000001.SZ,10.10,10.20,9.90,-1.00,12.00,800,8000,NORMAL\n\
2026-03-06,000001.SZ,10.00,9.00,9.50,9.80,8.50,900,9000,NORMAL\n\
2026-03-08,000001.SZ,10.20,10.40,10.10,10.30,10.20,1100,11000,NORMAL\n\
2026-03-07,000002.SZ,bad,10.10,9.90,10.00,10.00,500,5000,NORMAL\n",
    );

    let review_output_dir = dir.path().join("output/review");
    fs::create_dir_all(&review_output_dir).expect("mkdir review dir");
    write_file(
        &review_output_dir.join("disabled_issues.yaml"),
        "rules:\n  - rule_names: [\"DuplicateDatesRule\", \"NegativePriceRule\", \"TickSizeRule\"]\n    tickers: [\"000001.SZ\"]\n",
    );

    let cfg_path = dir.path().join("config.yaml");
        let cfg_content = vec![
                "mode: full".to_string(),
                "input:".to_string(),
                format!("  path: '{}'", csv_path.display()),
                "  format: csv".to_string(),
                "  schema:".to_string(),
                "    date: date".to_string(),
                "    ticker: ticker".to_string(),
                "    open: open".to_string(),
                "    high: high".to_string(),
                "    low: low".to_string(),
                "    close: close".to_string(),
                "    vwap: vwap".to_string(),
                "    volume: volume".to_string(),
                "    turnover: turnover".to_string(),
                "    status: status".to_string(),
                "rules:".to_string(),
                "  enabled_categories: ['DataIntegrity', 'IntraBarLogic']".to_string(),
                "  enabled_rules: []".to_string(),
                "  disabled_rules: []".to_string(),
                "handling:".to_string(),
                "  policies:".to_string(),
                "    - rule_name: VwapRangeRule".to_string(),
                "      action: clamp_field".to_string(),
                "      params:".to_string(),
                "        min_field: low".to_string(),
                "        max_field: high".to_string(),
                "    - rule_name: HighLowLogicRule".to_string(),
                "      action: set_literal".to_string(),
                "      params:".to_string(),
                "        value: '10.20'".to_string(),
        ]
        .join("\n");
    write_file(&cfg_path, &cfg_content);

    let cfg = load_and_validate_config(&cfg_path, &pipeline_registry()).expect("config valid");
    assert_eq!(cfg.mode, RunMode::Full);

    // 2) Loader.
    let load_out = load_data(&cfg).expect("load success");
    assert_eq!(load_out.records.len(), 4);
    assert_eq!(load_out.load_errors.len(), 1);

    // 3) Validator.
    let validation_plan = ValidationPlan::from_rule_switch(&cfg.rules);
    let validation_out = validate_records(
        &load_out.records,
        &default_validation_ctx(),
        &validation_plan,
        &ValidationRegistry::default(),
    )
    .expect("validation success");
    assert!(validation_out.total_issues > 0);
    assert!(validation_out
        .issues
        .iter()
        .any(|i| i.issue_type == IssueType::DuplicateDate));
    assert!(validation_out
        .issues
        .iter()
        .any(|i| i.issue_type == IssueType::VwapOutOfRange));

    // 4) Review stage: disable duplicate-date issues via review file.
    let review_cfg = ReviewConfig {
        charts: ReviewChartConfig {
            enabled: true,
            types: HashSet::from([
                ReviewChartType::IssueByDate,
                ReviewChartType::IssueByCategory,
                ReviewChartType::IssueByRule,
            ]),
        },
        preview: ReviewPreviewConfig {
            enabled: true,
            sample_size: 20,
        },
        output_dir: review_output_dir.clone(),
    };

    let review_stage = DefaultReviewStage::new(
        FileDisabledIssueProvider::default(),
        BasicReviewChartRenderer,
        wash_load::RuleBasedPreviewEngine::default(),
        FileReviewReportStore::default(),
    );
    let review_out = review_stage
        .run(&validation_out.issues, &review_cfg)
        .expect("review success");

    let approved_rule_names = review_out
        .approved_issues
        .iter()
        .map(|i| i.rule_name.as_str())
        .collect::<HashSet<_>>();
    let disabled_rule_names = review_out
        .disabled_issues
        .iter()
        .map(|i| i.rule_name.as_str())
        .collect::<HashSet<_>>();

    assert!(review_out
        .disabled_issues
        .iter()
        .any(|i| i.rule_name == "DuplicateDatesRule"));
    assert!(review_out
        .disabled_issues
        .iter()
        .any(|i| i.rule_name == "NegativePriceRule" || i.rule_name == "TickSizeRule"));
    assert!(!approved_rule_names.contains("DuplicateDatesRule"));
    assert!(!approved_rule_names.contains("NegativePriceRule"));
    assert!(!approved_rule_names.contains("TickSizeRule"));
    assert!(disabled_rule_names.contains("DuplicateDatesRule"));
    assert!(review_out.approved_issues.iter().any(|i| i.rule_name == "HighLowLogicRule"));
    assert!(review_out.approved_issues.iter().any(|i| i.rule_name == "VwapRangeRule"));
    assert!(review_output_dir.join("review_report.txt").exists());

    // 5) Cleaner stage.
    let cleaner = DefaultCleanerStage::new(
        RuleNamePolicyResolver,
        BuiltinPolicyExecutor,
        DefaultLoadErrorAuditMapper,
    );
    let cleaner_out = cleaner
        .run(
            &load_out.records,
            &review_out.approved_issues,
            &load_out.load_errors,
            &HandlingConfig {
                policies: cfg.handling.policies.clone(),
            },
        )
        .expect("clean success");

    // Expect unresolved issues due to rules without policy (for example NegativePriceRule).
    assert!(cleaner_out.unresolved_issues >= 1);
    assert!(cleaner_out
        .audit_entries
        .iter()
        .any(|e| e.action == "LOAD_ERROR"));
    assert!(cleaner_out
        .audit_entries
        .iter()
        .all(|e| e.rule_name != "DuplicateDatesRule"));
    assert!(cleaner_out
        .audit_entries
        .iter()
        .all(|e| e.rule_name != "NegativePriceRule"));
    assert!(cleaner_out
        .audit_entries
        .iter()
        .all(|e| e.rule_name != "TickSizeRule"));

    let repaired = cleaner_out
        .cleaned_records
        .iter()
        .find(|r| r.ticker == "000001.SZ" && r.date == "2026-03-06")
        .expect("repaired record exists");
    assert_eq!(repaired.high.to_string(), "10.20");
    assert_eq!(repaired.low.to_string(), "10.20");
    assert_eq!(repaired.vwap.to_string(), "10.20");
    assert!(repaired.vwap >= repaired.low && repaired.vwap <= repaired.high);

    // 6) Writer + audit log: keep outputs isolated under temp folder.
    let output_dir = dir.path().join("output/final");
    let cleaned_csv_path = output_dir.join("cleaned.csv");
    write_cleaned_csv(&cleaned_csv_path, &cleaner_out.cleaned_records);

    let rule_time_breakdown = validation_out
        .metrics
        .iter()
        .map(|m| (m.rule_name.clone(), m.elapsed.as_millis()))
        .collect::<HashMap<String, u128>>();

    let audit_json_path = output_dir.join("audit_log.json");
    let audit_csv_path = output_dir.join("audit_log.csv");
    let audit_service = DefaultAuditService::new(DefaultPerformanceSummaryBuilder, FileAuditLogWriter);
    let perf = audit_service
        .publish(
            &cleaner_out.audit_entries,
            wash_load::PerformanceSummaryInput {
                total_rows: load_out.records.len(),
                total_issues: validation_out.total_issues,
                disabled_issues: review_out.disabled_issues.len(),
                load_error_count: load_out.load_errors.len(),
                cleaner_output: &cleaner_out,
                total_time_ms: 321,
                rule_time_breakdown,
            },
            &audit_json_path,
            &audit_csv_path,
        )
        .expect("audit publish success");

    assert!(audit_json_path.exists());
    assert!(audit_csv_path.exists());

    // 7) Optional LLM report with mocked client (no real network call).
    let report_path = output_dir.join("report.md");
    let llm_service = DefaultLlmReportService::new(
        TopKSummaryBuilder,
        FileAuditCsvSampler,
        wash_load::SimplePromptBuilder,
        MockLlmClient,
        FileLlmReportStore,
    );

    let llm_out = llm_service
        .generate(
            &cleaner_out.audit_entries,
            &perf,
            &LlmReportConfig {
                enabled: true,
                model: "mock-gpt".to_string(),
                output_path: report_path.clone(),
                audit_csv_path: audit_csv_path.clone(),
                ..LlmReportConfig::default()
            },
        )
        .expect("llm pipeline success")
        .expect("report generated");

    assert_eq!(llm_out.report_path, report_path);
    assert!(llm_out.report_text.contains("Mock Full Pipeline Report"));
    assert!(report_path.exists());

    // 8) Versioning snapshot commit.
    let summary_path = output_dir.join("summary.json");
    write_summary_json(&summary_path, &perf);

    let versioning_cfg = VersioningConfig {
        history_dir: dir.path().join(".history"),
        head_file: "HEAD".to_string(),
        commits_dir: "commits".to_string(),
        checkpoint_dir: dir.path().join(".checkpoint"),
    };

    let versioning = DefaultVersioningService::new(FileHistoryStore, wash_load::EpochCommitIdStrategy);
    let commit_id = versioning
        .commit(
            &versioning_cfg,
            VersionCommitInput {
                author: "e2e-tester".to_string(),
                message: "full pipeline e2e".to_string(),
                run_mode: "full".to_string(),
                artifacts: CommitArtifacts {
                    config_yaml: cfg_path.clone(),
                    cleaned_csv: Some(cleaned_csv_path.clone()),
                    audit_log_json: Some(audit_json_path.clone()),
                    audit_log_csv: Some(audit_csv_path.clone()),
                    report_md: Some(report_path.clone()),
                    summary_json: summary_path.clone(),
                },
            },
        )
        .expect("commit success");

    let head = versioning
        .current_head(&versioning_cfg)
        .expect("read head")
        .expect("head exists");
    assert_eq!(head, commit_id);

    let commit_dir = versioning_cfg
        .history_dir
        .join("commits")
        .join(commit_id);
    assert!(commit_dir.join("config.yaml").exists());
    assert!(commit_dir.join("cleaned.csv").exists());
    assert!(commit_dir.join("audit_log.json").exists());
    assert!(commit_dir.join("audit_log.csv").exists());
    assert!(commit_dir.join("report.md").exists());
    assert!(commit_dir.join("summary.json").exists());
}

#[test]
fn recovery_plan_points_to_next_stage_after_checkpoint() {
    let dir = tempdir().expect("tempdir");

    let cfg = VersioningConfig {
        history_dir: dir.path().join(".history"),
        head_file: "HEAD".to_string(),
        commits_dir: "commits".to_string(),
        checkpoint_dir: dir.path().join(".checkpoint"),
    };

    let store = wash_load::FileCheckpointStore;
    store
        .save(&cfg, "run-e2e", wash_load::PipelineStage::Load, b"ok-load", None)
        .expect("save load");
    store
        .save(
            &cfg,
            "run-e2e",
            wash_load::PipelineStage::Validate,
            b"ok-validate",
            None,
        )
        .expect("save validate");

    let recovery = wash_load::DefaultRecoveryService::new(store);
    let plan = recovery
        .plan_resume(&cfg, "run-e2e")
        .expect("plan")
        .expect("should have plan");

    assert_eq!(plan.resume_from, wash_load::PipelineStage::Review);
}
